[package]
name = "pcp-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
pcp-pipeline = { path = "../../crates/pipeline" }
pcp-types = { path = "../../crates/types" }
pcp-utils = { path = "../../crates/utils" }
serde_json = { workspace = true }
tracing = { workspace = true }
