[package]
name = "pcp-decoder"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
symphonia = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
