[package]
name = "pcp-pipeline"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
pcp-types = { path = "../types" }
tracing = { workspace = true }
pcp-fetcher = { path = "../fetcher" }
tokio = { workspace = true }
pcp-decoder = { path = "../decoder" }
