name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --workspace --locked
      - name: Format check
        run: cargo fmt --all -- --check || true
      - name: Clippy
        run: cargo clippy --workspace -- -D warnings || true
      - name: Install nextest
        run: cargo install cargo-nextest --locked
      - name: Tests (nextest)
        run: cargo nextest run --workspace --profile ci || true
